### ISSUE TITLE
Illegal character in path cause errors.

### ISSUE THREAD

**Issue by gaycookie** [comp500/packwiz-installer#2]
```
Failed to download modpack, the following errors were encountered:
inventory-hud-forge.toml: com.google.gson.JsonParseException: Failed to parse URI
...
Caused by: java.net.URISyntaxException: Illegal character in path at index 61:
https://edge.forgecdn.net/files/3198/762/InventoryHUD-fabric-[1.16.2-1.16.5]-3.2.2.jar
```

inventory-hud-forge.toml
```
name = "Inventory HUD+"
filename = "InventoryHUD-fabric-[1.16.2-1.16.5]-3.2.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3198/762/InventoryHUD-fabric-[1.16.2-1.16.5]-3.2.2.jar"
hash-format = "murmur2"
hash = "3155476420"

[update]
[update.curseforge]
file-id = 3198762
project-id = 357540
release-channel = "beta"
```

Dear developers.

I stumbled on an error that kind of prevents me from using this module of Packwiz with my modpack
When I try to make it download the mods, it always errors on this exact same mod.
I do not know what I can do about it or if there is a way around it?

Greetings

**Comment by comp500** [comment]
Currently there's some issues with how packwiz-installer handles square brackets in URLs, a fix is planned but for now you can do the following workaround:
- Remove the square brackets in the destination filename
- Replace the square brackets in the URL with their encoded forms `%5B` and `%5D`

For the file you gave above that would be:
```toml
name = "Inventory HUD+"
filename = "InventoryHUD-fabric-1.16.2-1.16.5-3.2.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3198/762/InventoryHUD-fabric-%5B1.16.2-1.16.5%5D-3.2.2.jar"
hash-format = "murmur2"
hash = "3155476420"

[update]
[update.curseforge]
file-id = 3198762
project-id = 357540
release-channel = "beta"

```
